// ReSharper disable InconsistentNaming
namespace HearthStone.Mirror.Enums
{
  public enum GameState
  {
    s_instance = 0,
    s_gameStateInitializedListeners = 4,
    m_entityMap = 8,
    m_playerMap = 12,
    m_gameEntity = 16,
    m_realTimeGameOverTagChange = 20,
    m_choicesMap = 24,
    m_queuedChoices = 28,
    m_chosenEntities = 32,
    m_options = 36,
    m_selectedOption = 40,
    m_lastOptions = 44,
    m_lastSelectedOption = 48,
    m_friendlyCardBeingDrawn = 52,
    m_opponentCardBeingDrawn = 56,
    m_createGameListeners = 60,
    m_optionsReceivedListeners = 64,
    m_optionsSentListeners = 68,
    m_optionRejectedListeners = 72,
    m_entityChoicesReceivedListeners = 76,
    m_entitiesChosenReceivedListeners = 80,
    m_currentPlayerChangedListeners = 84,
    m_friendlyTurnStartedListeners = 88,
    m_turnChangedListeners = 92,
    m_spectatorNotifyListeners = 96,
    m_gameOverListeners = 100,
    m_heroChangedListeners = 104,
    m_powerProcessor = 108,
    m_serverBlockingSpells = 112,
    m_serverBlockingSpellControllers = 116,
    m_turnTimerUpdateListeners = 120,
    m_mulliganTimerUpdateListeners = 124,
    m_turnTimerUpdates = 128,
    m_waitForOpponentReconnectPopup = 132,
    m_waitForOpponentReconnectPopupInfo = 136,
    m_createGamePhase = 140,
    m_gameOver = 144,
    m_concedeRequested = 145,
    m_restartRequested = 146,
    m_maxSecretZoneSizePerPlayer = 148,
    m_maxSecretsPerPlayer = 152,
    m_maxQuestsPerPlayer = 156,
    m_maxFriendlyMinionsPerPlayer = 160,
    m_responseMode = 164,
    m_coinHasSpawned = 168,
    m_lastTurnRemindedOfFullHand = 172,
    m_usingFastActorTriggers = 176,
    m_reconnectIfStuckTimer = 180,
    m_lastBlockedReportTimestamp = 184,
    m_busy = 188,
    m_mulliganBusy = 189
  }
}
